[console_conf]
switch = true
debug = true
info = true 
warn = true 
error = true
fatal = true

[file_conf]
switch = true
debug = true
info = true 
warn = true 
error = true
fatal = true

file_log_dir = "/tmp/log/" 
file_temp_buf = "1048576"
